export const CALENDAR_ROUTE = '/calendar'
export const CHAT_ROUTE = '/chat'
export const FRIENDS_ROUTE = '/friends'
export const GOALS_ROUTE = '/goals'
export const HABITS_ROUTE = '/habits'
export const MY_DAY_ROUTE = '/my_day'
export const PROFILE_ROUTE = '/profile'
export const TASKS_ROUTE = '/tasks'
export const REGISTRATION_ROUTE = '/registration'
export const LOGIN_ROUTE = '/login'
export const DEFAULT_ROUTE = '/'

export const SET_IS_AUTH_ACTION = 'SET_IS_AUTH'
export const SET_USER_ACTION = 'SET_USER'

export const ADD_TASK_ACTION = 'ADD_TASK'
export const LOAD_TASKS_ACTION = 'LOAD_TASKS'
export const UPDATE_TASK_ACTION = 'UPDATE_TASK'
export const DELETE_TASK_ACTION = 'DELETE_TASK'